//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityGroupList
    {
        public int Id { get; set; }
        public int Activity_Id { get; set; }
        public int ActivityGroup_Id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ActivityGroup ActivityGroup { get; set; }
    }
}
