//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WLATrx
    {
        public int Id { get; set; }
        public int Process_Time { get; set; }
        public int Frequency { get; set; }
        public double Sub_Total_Aktivitas { get; set; }
        public double Effective_Working_Hours { get; set; }
        public double FTE { get; set; }
        public double Presentase { get; set; }
    
        public virtual Fungsi Fungsi { get; set; }
        public virtual Jabatan Jabatan { get; set; }
        public virtual Pelaksana Pelaksana { get; set; }
        public virtual Periode Periode { get; set; }
    }
}
