//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeGroup
    {
        public int Id { get; set; }
        public int Process_Time { get; set; }
        public int Frequency { get; set; }
        public int Quantity { get; set; }
        public double Effective_Working_Hours { get; set; }
        public double FTE { get; set; }
        public int WLAHeader_Id { get; set; }
        public int ActivityGroup_Id { get; set; }
    
        public virtual ActivityGroup ActivityGroup { get; set; }
        public virtual WLAHeader WLAHeader { get; set; }
    }
}
