//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard_Time
    {
        public int Id { get; set; }
        public int Tahun { get; set; }
        public int Day { get; set; }
        public int Saturday { get; set; }
        public int Sunday { get; set; }
        public int Holiday { get; set; }
        public int Annual_Leaves { get; set; }
        public int Sick_Permission { get; set; }
        public int Working_Days { get; set; }
        public int Effective_Working_Days { get; set; }
        public int Working_Hours { get; set; }
        public double Utilitation_Level { get; set; }
        public double Effective_Working_Hours { get; set; }
    }
}
