//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WLAHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WLAHeader()
        {
            this.ResumeGroups = new HashSet<ResumeGroup>();
            this.WLATrxes = new HashSet<WLATrx>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Tahun { get; set; }
        public double FTE { get; set; }
        public int Fungsi_Id { get; set; }
        public int Jabatan_Id { get; set; }
        public Nullable<double> Effective_Working_Hours { get; set; }
    
        public virtual Fungsi Fungsi { get; set; }
        public virtual Jabatan Jabatan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumeGroup> ResumeGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WLATrx> WLATrxes { get; set; }
    }
}
